// Generated by CoffeeScript 1.7.1
(function() {
  exports.configure = function(expressApp, registerCallback) {
    var nodeStatic, staticServer;
    nodeStatic = require('node-static');
    staticServer = new nodeStatic.Server('./public');
    expressApp.post('/landing/register', registerCallback);
    expressApp.get('/landing', function(req, res) {
      return staticServer.serveFile('landing/index.html', 200, {}, req, res);
    });
    return expressApp.get(/\/landing\/.*/, function(req, res) {
      return staticServer.serve(req, res);
    });
  };

}).call(this);
